### ISSUE TITLE
Question about the address to pull the Singularity image 

### ISSUE THREAD

**Issue by Luosanj** [porchard/snATACseq-NextFlow#2]
Hi,
    I met a bug when processing the raw sequencing. fastq snATAC-seq data. The bug is that the Singularity image failed to be pulled to the Cache in the set repository. I can pull it manually, but I do not know where to pull that image into the Cache. May you help me check this issue? Thanks a lot!

Best,
<img width="1468" alt="image" src="https://github.com/user-attachments/assets/a31c28e2-354f-4cad-96e9-c18f18bbc34e">

**Comment by porchard** [comment]
Hi @Luosanj,

Odd -- it should normally take a few minutes to pull the image, then proceed to submit the jobs. The above message makes it look like it's trying to submit jobs immediately using an incomplete image? Can you share your `nextflow.config`, verify you've loaded the singularity module, and give the NextFlow/Singularity versions?

**Comment by porchard** [comment]
It looks like I get a very similar error when singularity isn't loaded -- perhaps that's the issue?

**Comment by Luosanj** [comment]
Hi Peter,
     Yes. I have downloaded the image manually. Now this problem has been solved!
